repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        stages: [commit]
        entry: black
        pass_filenames: true
        files: '.*\.py$'
        language: system
-   repo: local
    hooks:
    -   id: lint
        name: lint
        stages: [commit]
        entry: pylint
        pass_filenames: true
        files: '.*\.py$'
        language: system
-   repo: local
    hooks:
    -   id: test
        name: test
        stages: [commit]
        types: [python]
        entry: pytest
        files: '.*_test\.py$'
        pass_filenames: true
        always_run: false
        language: system
